name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src/
    - name: Build
      run: dotnet build src/ --configuration Release
    - name: Test with the dotnet CLI
      run: dotnet test src/
    - name: Pack with dotnet
      run: dotnet pack src/Orleans.Telemetry.ApplicationInsights/Orleans.Telemetry.ApplicationInsights.csproj --output nuget --configuration Release      
    - name: Upload Assembly Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build output
        path: /home/runner/work/Orleans.Telemetry.ApplicationInsights/Orleans.Telemetry.ApplicationInsights/src/Orleans.Telemetry.ApplicationInsights/bin/Release/net7.0/
    - name: Upload Package Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Package output
        path: nuget/*.nupkg     
    - name: Publish NuGet using Dotnet
      run: dotnet nuget push nuget/*.nupkg --api-key ${{secrets.NUGET}} --skip-duplicate --source https://api.nuget.org/v3/index.json
